from animalia import *

print("-"*100)
animal1= Animal("Animal", "verde", 4, "sonido")
print(animal1.nombre)
print(animal1.color)
print(animal1.patas)
animal1.sound()

print("-"*100)
animal2= Conejo("Juan", "blanco", 4, "skeee")
print(animal2.nombre)
print(animal2.color)
print(animal2.patas)
animal2.sound()
animal2.pres1()

print("-"*100)
animal3= Ormi("Jorge", "gris", 4, "click", "mediano")
print(animal3.nombre)
print(animal3.color)
print(animal3.patas)
print(animal3.pico)
animal3.sound()
animal3.pres2()

print("-"*100)
animal3= Ormi("Oliver", "verde", 2, "rawr", "t-rex")
print(animal3.nombre)
print(animal3.color)
print(animal3.patas)
print(animal3.pico)
animal3.sound()
animal3.pres2()