from humane import *
print("-"*100)
humano1= Humano("Diana", 17, "mujer")
print(humano1.nombre)
print(humano1.edad)
print(humano1.genero)
humano1.caract()
humano1.saludo()

print("-"*100)
programador1= Programador("Juan", 19, "hombre")
print(programador1.nombre)
print(programador1.edad)
print(programador1.genero)
programador1.saludo2()

print("-"*100)
licenciado1= Licenciado("Edgar", 24, "hombre", 222777111)
print(licenciado1.nombre)
print(licenciado1.edad)
print(licenciado1.genero)
print(licenciado1.telefono)
licenciado1.caract()
licenciado1.saludo()
print("-"*100)